MODULES=(btrfs nvidia nvidia_modeset nvidia_uvm nvidia_drm cmac uhid usbhid xhci_hcd) 
BINARIES=(/usr/bin/btrfs)
FILES=()
HOOKS=(base udev keyboard autodetect keymap bluetooth numlock modconf block encrypt filesystems fsck)
