# -----------------------------------------------------
# Keyboard Layout
# https://wiki.hyprland.org/Configuring/Variables/#input
# -----------------------------------------------------
input {
    kb_layout = br
    kb_variant = dvorak
    kb_model =
    kb_options =

    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    numlock_by_default = true
}

device {
    name = corne-keyboard
    kb_layout = us
    kb_variant = intl
    resolve_binds_by_sym = 1
}
device {
    name = zmk-project-corne-keyboard
    kb_layout = us
    kb_variant = intl
    resolve_binds_by_sym = 1
}
